[package]
name = "bnb"
description = "A generic template for Branch & Bound algorithms"
version = "0.1.2"
edition = "2021"
authors = ["Lukas Geis <lukasgeis@gmx.de>"]
license = "MIT"
exclude = [".gitignore", "target"]
homepage = "https://github.com/lukasgeis/bnb"


[dependencies]
